apiVersion: v1
data:
  cluster.name: "{{ .Values.cluster_name }}"
  http.port: "2020"
  http.server: "On"
  logs.region: "{{ .Values.region }}"
  read.head: "Off"
  read.tail: "On"
kind: ConfigMap
metadata:
  name: fluent-bit-cluster-info
  namespace: amazon-cloudwatch

